# Generated by Django 5.0.7 on 2024-07-27 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_distance', models.FloatField()),
                ('walking_distance', models.FloatField()),
                ('pub1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='pubs.pub')),
                ('pub2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='pubs.pub')),
            ],
            options={
                'unique_together': {('pub1', 'pub2')},
            },
        ),
    ]
