# Generated by Django 5.0.7 on 2024-07-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0002_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='fas_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pub',
            name='latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pub',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
