# Generated by Django 5.0.7 on 2024-07-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0006_remove_pub_local_authority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub',
            old_name='local_authority2',
            new_name='local_authority',
        ),
    ]
