# Generated by Django 5.0.7 on 2024-07-29 21:00

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0007_rename_local_authority2_pub_local_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
