# Generated by Django 5.0.7 on 2024-07-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0008_pub_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='longitude',
        ),
    ]
