# Generated by Django 5.0.7 on 2024-08-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0009_remove_pub_latitude_remove_pub_longitude'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='distance',
            index=models.Index(fields=['pub1', 'pub2'], name='pubs_distan_pub1_id_f3522c_idx'),
        ),
    ]
