# Generated by Django 5.0.7 on 2024-08-01 07:55

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0010_distance_pubs_distan_pub1_id_f3522c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
