# Generated by Django 5.0.7 on 2024-08-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0011_pub_geo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='location',
        ),
    ]
